# Generated by Django 4.2.3 on 2023-07-07 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_myinfo_image_works_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinfo',
            name='intro',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myinfo',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
